version: '3.8'

services:
  node:
    container_name: node
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - cassandra1
      - cassandra2
      - cassandra3
  cassandra1:
    container_name: cassandra1
    image: bitnami/cassandra:3.0.27
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_PASSWORD_SEEDER=yes
    volumes:
      - ./cassandra/db:/docker-entrypoint-initdb.d
      - ./cassandra/persistence:/bitnami
  cassandra2:
    container_name: cassandra2
    image: bitnami/cassandra:3.0.27
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
  cassandra3:
    container_name: cassandra3
    image: bitnami/cassandra:3.0.27
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3