version: '3.8'

services:
  node:
    container_name: node
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - cassandra1
      - cassandra2
    networks:
      - cluster
  cassandra1:
    container_name: cassandra1
    image: bitnami/cassandra:4.0.4
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_PASSWORD_SEEDER=yes
    networks:
      - cluster
  cassandra2:
    container_name: cassandra2
    image: bitnami/cassandra:4.0.4
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra1,cassandra2
    networks:
      - cluster
networks:
  cluster:
    driver: bridge
